#!/bin/sh
uci -q batch <<-UCIBATCH >/dev/null
	delete ucitrack.@miaplus[-1]
	add ucitrack miaplus
	set ucitrack.@miaplus[-1].init=miaplus
	set ucitrack.@miaplus[-1].exec='/etc/init.d/miaplus reload'
	set ucitrack.@miaplus[-1].exec='/etc/init.d/miaplus restart'
	commit ucitrack
	delete firewall.miaplus
	set firewall.miaplus=include
	set firewall.miaplus.type=script
	set firewall.miaplus.path=/etc/miaplus.include
	set firewall.miaplus.reload=1
	commit firewall
UCIBATCH
rm -f /tmp/luci-indexcache
exit 0
