name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          COMMIT=`(printf "commit %s\0" $(git cat-file commit HEAD | wc -c); git cat-file commit HEAD) | sha1sum | cut -c1-8`
          echo "COMMIT=$COMMIT" >> $GITHUB_ENV

      - name: Build
        uses: kingyond/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          PACKAGES: luci-app-accesscontrol-plus
          CUSTOM_PKG_DIR: luci-app-accesscontrol-plus
          CUSTOM_SRC_DIR: luci-app-accesscontrol-plus

      - name: Test
        run: |
          ls -R bin

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch}}-packages
          path: |
            bin/packages/${{ matrix.arch }}/base/luci-app-accesscontrol-plus*.ipk

      - name: Deploy Files To Release (Tag)
        uses: ncipollo/release-action@v1.8.0
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "bin/packages/${{ matrix.arch }}/base/luci-app-accesscontrol-plus*.ipk, bin/packages/${{ matrix.arch }}/base/luci-i18n-accesscontrol-plus*.ipk"

      - name: Deploy Files To Release (Commit)
        uses: ncipollo/release-action@v1.8.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.COMMIT }}
          artifacts: "bin/packages/${{ matrix.arch }}/base/luci-app-accesscontrol-plus*.ipk, bin/packages/${{ matrix.arch }}/base/luci-i18n-accesscontrol-plus*.ipk"
